// @ts-nocheck
// GENERATED BY `pnpm contracts:gen` — DO NOT EDIT.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async createSession() : Promise<Result<SessionDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSessions() : Promise<Result<SessionDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeSession(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEvents(sessionId: string, afterSeq: number) : Promise<Result<EventDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_events", { sessionId, afterSeq }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async submitTask(sessionId: string, input: string) : Promise<Result<RunResultDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_task", { sessionId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enqueueMessage(sessionId: string, input: string) : Promise<Result<MessageQueueItemDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enqueue_message", { sessionId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMessageQueue(sessionId: string) : Promise<Result<MessageQueueItemDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_message_queue", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelMessageQueueItem(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_message_queue_item", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearMessageQueue(sessionId: string) : Promise<Result<number, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_message_queue", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTask(title: string, description: string) : Promise<Result<TaskDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_task", { title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTasks(status: string | null) : Promise<Result<TaskDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tasks", { status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTaskStatus(taskId: string, status: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_task_status", { taskId, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTask(taskId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_task", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRun(runId: string) : Promise<Result<RunDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_run", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRunsByTask(taskId: string) : Promise<Result<RunDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_runs_by_task", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPendingApprovals() : Promise<Result<ApprovalDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_pending_approvals") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveApproval(approvalId: string, approved: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_approval", { approvalId, approved }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDir(path: string) : Promise<Result<FileEntryDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(path: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFile(path: string, content: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStatus() : Promise<Result<GitStatusDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitLog(limit: number) : Promise<Result<GitCommitDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_log", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStage(paths: string[]) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_stage", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitCommit(message: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_commit", { message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPush(remote: string, branch: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_push", { remote, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitWorktrees() : Promise<Result<GitWorktreeDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_worktrees") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitDiff(path: string, staged: boolean) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_diff", { path, staged }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStagedDiff() : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_staged_diff") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCommitAgents() : Promise<Result<CommitAgentOptionDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_commit_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiCommitGenerate(roleAgent: AgentRefInput | null) : Promise<Result<AiCommitResultDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_commit_generate", { roleAgent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSchedule(name: string, cronExpr: string, taskTitle: string, taskDescription: string) : Promise<Result<ScheduleDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_schedule", { name, cronExpr, taskTitle, taskDescription }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSchedules() : Promise<Result<ScheduleDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_schedules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleSchedule(scheduleId: string, enabled: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_schedule", { scheduleId, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSchedule(scheduleId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_schedule", { scheduleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertProvider(provider: ProviderInput) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviders() : Promise<Result<ProviderDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_providers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProvider(providerId: string, force: boolean | null) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_provider", { providerId, force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testProviderConnection(input: TestProviderConnectionInput) : Promise<Result<TestProviderConnectionDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_provider_connection", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviderModels(input: ListProviderModelsInput) : Promise<Result<ListProviderModelsDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_provider_models", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSensitiveTools(patterns: string[]) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sensitive_tools", { patterns }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSensitiveTools() : Promise<Result<string[] | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sensitive_tools") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOnlineAuthorized(authorized: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_online_authorized", { authorized }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOnlineAuthorized() : Promise<Result<boolean, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_online_authorized") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEvolutionSettings() : Promise<Result<EvolutionSettingsDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_evolution_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setEvolutionSettings(settings: EvolutionSettingsDto) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_evolution_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkspace() : Promise<Result<WorkspaceInfo, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWorkspace(path: string) : Promise<Result<WorkspaceInfo, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_workspace", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkspaces() : Promise<Result<WorkspaceEntryDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspaces") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addWorkspace(path: string) : Promise<Result<WorkspaceEntryDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_workspace", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeWorkspace(id: string) : Promise<Result<RemoveWorkspaceResult, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_workspace", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activateWorkspace(id: string) : Promise<Result<WorkspaceEntryDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_workspace", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveWorkspace() : Promise<Result<WorkspaceEntryDto | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_workspace") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOrphanSessions() : Promise<Result<OrphanSessionDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_orphan_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reclaimOrphanSessions(workspaceId: string) : Promise<Result<number, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reclaim_orphan_sessions", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgentProfiles() : Promise<Result<AgentProfileDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agent_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertAgentProfile(profile: AgentProfileInput) : Promise<Result<AgentProfileDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_agent_profile", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAgentProfile(profileId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_agent_profile", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkCliAgent(profileId: string) : Promise<Result<CliAgentCheckDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_cli_agent", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRoles() : Promise<Result<RoleDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_roles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertRole(role: RoleInput) : Promise<Result<RoleDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_role", { role }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRole(roleId: string, force: boolean | null) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_role", { roleId, force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seedBuiltinRoles() : Promise<Result<SeedRolesDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("seed_builtin_roles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateRole(description: string) : Promise<Result<RoleDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_role", { description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRoutingRules() : Promise<Result<RoutingRulesDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_routing_rules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setRoutingRules(rules: RoutingRulesDto) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_routing_rules", { rules }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async routeCapability(request: RouteRequestDto) : Promise<Result<RouteResultDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("route_capability", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async journalRollback(seq: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("journal_rollback", { seq }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTeams() : Promise<Result<TeamDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_teams") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertTeam(team: TeamInput) : Promise<Result<TeamDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_team", { team }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTeam(teamId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_team", { teamId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWhiteboardNotes(sessionId: string) : Promise<Result<WhiteBoardNoteDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_whiteboard_notes", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async formTeam(task: string, sessionId: string | null) : Promise<Result<TeamDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("form_team", { task, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewTeam(task: string) : Promise<Result<TeamPlanDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_team", { task }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runTeamOnTask(taskId: string, teamId: string) : Promise<Result<RunDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_team_on_task", { taskId, teamId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runTeamSession(sessionId: string, teamId: string, task: string) : Promise<Result<TeamRunResultDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_team_session", { sessionId, teamId, task }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listIntegrations() : Promise<Result<IntegrationDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_integrations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertIntegration(input: IntegrationInput) : Promise<Result<IntegrationDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_integration", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteIntegration(integrationId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_integration", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testIntegration(integrationId: string) : Promise<Result<TestIntegrationDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_integration", { integrationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginList() : Promise<Result<PluginListResultDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginInstallFromPath(path: string) : Promise<Result<PluginInfoDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_install_from_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginUninstall(pluginId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_uninstall", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginOpenDir() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_open_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginEditorCall(pluginId: string, method: string, params: JsonValue) : Promise<Result<JsonValue, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_editor_call", { pluginId, method, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appSettingGet(key: string) : Promise<Result<string | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_setting_get", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appSettingSet(key: string, value: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_setting_set", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createConversation(input: ConversationInput) : Promise<Result<ConversationDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_conversation", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listConversations(kind: string | null) : Promise<Result<ConversationDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_conversations", { kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConversation(sessionId: string) : Promise<Result<ConversationDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conversation", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setConversationAgent(sessionId: string, agent: AgentRefInput | null) : Promise<Result<ConversationDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_conversation_agent", { sessionId, agent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgentOptions() : Promise<Result<AgentOptionDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agent_options") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConversation(sessionId: string, input: ConversationUpdateInput) : Promise<Result<ConversationDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_conversation", { sessionId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addConversationAgent(sessionId: string, agent: AgentRefInput) : Promise<Result<ConversationDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_conversation_agent", { sessionId, agent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeConversationAgent(sessionId: string, agent: AgentRefInput) : Promise<Result<ConversationDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_conversation_agent", { sessionId, agent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteConversation(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_conversation", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearConversations() : Promise<Result<number, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_conversations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAgentDetail(agentKind: string, agentId: string) : Promise<Result<AgentDetailDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent_detail", { agentKind, agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async submitMessage(sessionId: string, text: string, attachmentIds: string[], routeTargetAgentIds: string[] | null, contextInjectionIds: string[] | null) : Promise<Result<RunResultDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_message", { sessionId, text, attachmentIds, routeTargetAgentIds, contextInjectionIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopConversation(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_conversation", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listActiveRuns() : Promise<Result<RunDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_active_runs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelRun(runId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_run", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAttachment(sessionId: string, name: string, mime: string, dataBase64: string) : Promise<Result<AttachmentDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_attachment", { sessionId, name, mime, dataBase64 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAttachments(sessionId: string) : Promise<Result<AttachmentDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_attachments", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAttachment(attachmentId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_attachment", { attachmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertSchedule(input: ScheduleInput) : Promise<Result<ScheduleDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_schedule", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSchedule(scheduleId: string, input: ScheduleInput) : Promise<Result<ScheduleDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_schedule", { scheduleId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async injectContext(sessionId: string, input: ContextInjectionInput) : Promise<Result<ContextInjectionDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inject_context", { sessionId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInjectableSessions() : Promise<Result<InjectableSessionDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_injectable_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInjectableRules() : Promise<Result<InjectableRuleDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_injectable_rules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribeAudio(audioBase64: string, modelSource: string | null) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio", { audioBase64, modelSource }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAsrModels() : Promise<Result<AsrModelDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_asr_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Frontend heartbeat: called once after the React root mounts to signal that
 * the webview is alive. If this never arrives within the watchdog grace
 * period, the shell auto-reloads the webview (see `shell_resilience`).
 */
async nuomiHeartbeat() : Promise<void> {
    await TAURI_INVOKE("__nuomi_heartbeat");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentDetailDto = { kind: string; id: string; name: string; avatarUrl: string | null; role: string | null; responsibility: string | null; boundModel: string | null; provider: string | null; 
/**
 * 绑定来源："provider" | "cli" | null。配合 provider/cli_agent_* 字段使用。
 */
bindingKind?: string | null; 
/**
 * CLI Agent 名称（binding_kind="cli" 时填充）。
 */
cliAgentName?: string | null; 
/**
 * CLI Agent 方言："claude_code" | "codex" | "plain"。
 */
cliAgentFlavor?: string | null; 
/**
 * CLI Agent 模型标识（来自 AgentProfile.model_id）。
 */
cliAgentModel?: string | null; enabled: boolean }
export type AgentOptionDto = { kind: string; id: string; name: string; enabled: boolean; builtin: boolean; role: string | null; responsibility: string | null; boundModel: string | null; provider: string | null }
export type AgentProfileDto = { id: string; name: string; adapter: string; flavor: CliFlavorDto; command: string; args: string[]; env: Partial<{ [key in string]: string }>; workingDir: string | null; enabled: boolean; modelId: string | null; 
/**
 * CLI 会话保持参数模板（ADR 0012 D6）。
 */
resumeArgs?: string | null; createdAt: number; updatedAt: number }
export type AgentProfileInput = { name: string; flavor: CliFlavorDto; command: string; args: string[]; env: Partial<{ [key in string]: string }>; workingDir: string | null; enabled: boolean; modelId?: string | null; 
/**
 * CLI 会话保持参数模板（ADR 0012 D6）。如 `--resume {session_id}`。
 */
resumeArgs?: string | null }
export type AgentRefDto = { kind: string; id: string; name: string }
export type AgentRefInput = { kind: string; id: string }
export type AiCommitResultDto = { message: string; truncated: boolean; agentName: string; elapsedMs: number }
export type ApprovalDto = { id: string; runId: string; toolName: string; argumentsJson: string }
export type AsrModelDto = { id: string; name: string; provider: string; builtin: boolean }
export type AttachmentDto = { id: string; sessionId: string; seq: number | null; kind: string; name: string; mime: string; relPath: string; sizeBytes: number; sha256: string; createdAt: number }
/**
 * System modality capability (mirrors `nuomi_core::domain::Capability`).
 */
export type CapabilityDto = "reasoning" | "image" | "voice" | "video"
export type CliAgentCheckDto = { ok: boolean; versionLine: string | null; error: string | null }
export type CliFlavorDto = "claude_code" | "codex" | "plain"
export type CommitAgentOptionDto = { kind: string; id: string; name: string; isDefault: boolean }
export type ContextInjectionDto = { id: string; sessionId: string; type: string; refId: string | null; text: string | null; status: string; createdAt: number }
export type ContextInjectionInput = { type: string; refId: string | null; text: string | null }
export type ConversationDto = { id: string; title: string; kind: string; teamId: string | null; taskId: string | null; scheduleId: string | null; createdAt: number; updatedAt: number; goal: string | null; mainAgentId: string | null; routeMode: string | null; whiteboardRouteMode: string | null; participantAgents: AgentRefDto[]; todoList: TodoItemDto[] }
export type ConversationInput = { kind: string; title: string | null; agent: AgentRefInput | null; teamId: string | null }
export type ConversationUpdateInput = { title: string | null; goal: string | null }
/**
 * One `[[editor.commands]]` entry (ADR 0010).
 */
export type EditorCommandDto = { name: string; title: string; tool: string }
/**
 * The plugin manifest's `[editor]` section (ADR 0010). Present only when the
 * plugin declares editor contributions.
 */
export type EditorContributionDto = { 
/**
 * Monaco language ids served; `["*"]` = all.
 */
languages: string[]; 
/**
 * Plugin implements the `editor/hover` NPP method.
 */
hover: boolean; 
/**
 * Plugin implements the `editor/symbols` NPP method.
 */
symbols: boolean; commands: EditorCommandDto[]; overlays: EditorOverlayDto[] }
/**
 * One `[[editor.overlays]]` entry (ADR 0010): URL rendered in a sandboxed
 * iframe overlay by the shell.
 */
export type EditorOverlayDto = { id: string; title: string; url: string; width: number; height: number }
export type EventDto = { seq: number; kind: string; payload: JsonValue; createdAt: number }
export type EvolutionSettingsDto = { onlineLearning: OnlineLearningConfigDto; refine: RefineConfigDto; skillCreation: SkillCreationConfigDto; memoryPolicy: MemoryPolicyDto }
export type FileEntryDto = { name: string; isDir: boolean; size: number }
export type GitCommitDto = { hash: string; subject: string; author: string }
export type GitStatusDto = { indexStatus: string; worktreeStatus: string; path: string }
export type GitWorktreeDto = { path: string; head: string | null; branch: string | null; isCurrent: boolean }
export type InjectableRuleDto = { id: string; name: string; systemPrompt: string | null }
export type InjectableSessionDto = { id: string; title: string; kind: string; updatedAt: number }
/**
 * IPC-safe integration view. The webhook URL crosses the boundary masked
 * only (write-only field: stored raw in SQLite per SPEC D5, never read
 * back); the secret never leaves the process at all.
 */
export type IntegrationDto = { id: string; name: string; kind: IntegrationKindDto; webhookUrlMasked: string; events: string[]; enabled: boolean; createdAt: number; updatedAt: number }
export type IntegrationInput = { name: string; kind: IntegrationKindDto; webhookUrl: string; 
/**
 * Feishu signing secret; persisted into `config.secret` for
 * `feishu_bot` rows only.
 */
secret: string | null; 
/**
 * Optional extra headers for generic webhook/telemetry endpoints.
 */
headers: Partial<{ [key in string]: string }> | null; 
/**
 * Trigger-topic whitelist (empty = all domain topics on dispatch).
 */
events: string[]; enabled: boolean }
export type IntegrationKindDto = "feishu_bot" | "qq_webhook" | "telemetry"
/**
 * Outward-facing error for every command.
 */
export type IpcError = { generic: { code: string; message: string; details?: JsonValue | null } }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type ListProviderModelsDto = { 
/**
 * Sorted, de-duplicated ids exposed by `GET {base_url}/models`.
 */
models: string[]; 
/**
 * Set instead of an IPC error on transport/HTTP/parse failures, so the
 * settings form keeps the previously fetched list on screen.
 */
error: string | null }
export type ListProviderModelsInput = { 
/**
 * When set and `api_key` is empty, the stored keyring secret is used.
 */
providerId: string | null; protocol: ProviderProtocolDto; baseUrl: string; apiKey: string | null; 
/**
 * Overrides the stored per-provider proxy when non-empty.
 */
proxy: string | null }
export type MemoryPolicyDto = { retentionDays: number; retrieval: RetrievalStrategyDto }
export type MessageQueueItemDto = { id: string; text: string; seq: number; createdAt: number }
/**
 * One model exposed by a provider endpoint plus its capability tags
 * (KiloCode-style per-model capabilities).
 */
export type ModelEntryDto = { id: string; capabilities: CapabilityDto[]; temperature?: number | null; topP?: number | null; maxTokens?: number | null }
export type OnlineLearningConfigDto = { authorized: boolean; allowlist: string[] }
/**
 * A session whose `workspace_id` points to a removed workspace.
 */
export type OrphanSessionDto = { sessionId: string; workspaceId: string; title: string; updatedAt: number }
export type PluginInfoDto = { id: string; name: string; version: string; apiVersion: number; description: string | null; 
/**
 * env | config | user | workspace (loader SourceKind label).
 */
source: string; 
/**
 * Absolute plugin directory (display + "reveal" affordances).
 */
dir: string; 
/**
 * True when the panel may uninstall it (source = user config dir).
 */
uninstallable: boolean; 
/**
 * Fully-qualified tool names (`<id>.<tool>`).
 */
tools: string[]; hooks: string[]; events: string[]; 
/**
 * Editor contributions (ADR 0010); `None` when the manifest has no
 * `[editor]` section.
 */
editor: EditorContributionDto | null; permissions: PluginPermissionsDto }
export type PluginListResultDto = { plugins: PluginInfoDto[]; skipped: string[]; failed: string[] }
/**
 * Declared permission surface of one plugin (panel display only, v1).
 */
export type PluginPermissionsDto = { fsRead: string[]; fsWrite: string[]; network: string[]; shell: boolean }
export type ProviderDto = { id: string; name: string; protocol: ProviderProtocolDto; baseUrl: string; hasKey: boolean; capabilities: string[]; isMaster: boolean; settings: ProviderSettingsDto }
export type ProviderInput = { 
/**
 * `None` inserts a fresh row; `Some(id)` updates that row in place.
 */
id: string | null; name: string; protocol: ProviderProtocolDto; baseUrl: string; capabilities: string[]; isMaster: boolean; 
/**
 * Plaintext only in transit — stored straight into the OS keyring,
 * never persisted to SQLite or logs.
 */
apiKey: string | null; 
/**
 * Model/routing settings (persisted inside `params_json`).
 */
settings: ProviderSettingsDto }
export type ProviderProtocolDto = "open_ai_compatible" | "anthropic_compatible"
/**
 * Provider-level settings mirrored from
 * `nuomi_core::domain::entities::ProviderSettings` (stored inside the
 * provider row's `params_json` under the `"settings"` key).
 */
export type ProviderSettingsDto = { 
/**
 * Per-model entries with capability tags. Legacy string model ids are
 * normalized to `{ id, capabilities: ["reasoning"] }` by the entity.
 */
models?: ModelEntryDto[]; defaultModel?: string | null; temperature?: number | null; topP?: number | null; maxTokens?: number | null; timeoutSecs?: number | null; retry?: number | null; maxConcurrency?: number | null; priority?: number | null; roles?: string[]; 
/**
 * Per-provider local network proxy (`http://host:port`); `None` = direct.
 */
proxy?: string | null; enabled?: boolean }
export type RefineConfigDto = { triggerFailures: number; minEditStrategy: RefineStrategyDto; evidenceThreshold: number; rollbackEnabled: boolean }
export type RefineStrategyDto = "prompt_note" | "memory" | "skill" | "sub_agent_spec"
/**
 * Result of removing a workspace: the removed id plus the new active id
 * (None when the registry is now empty).
 */
export type RemoveWorkspaceResult = { removedId: string; newActiveId: string | null }
export type RetrievalStrategyDto = "keyword" | "semantic" | "hybrid"
export type RoleDto = { id: string; name: string; providerId: string | null; providerIds: string[]; systemPromptOverride: string | null; toolAllowlist: string[]; requiredCapabilities: CapabilityDto[]; temperature: number | null; maxTokens: number | null; params: JsonValue; builtin: boolean; generated: boolean; ephemeral: boolean; source: JsonValue; createdAt: number; updatedAt: number }
export type RoleInput = { name: string; providerId: string | null; 
/**
 * Multi-provider bindings (Agent = Role + Provider); merged with
 * `provider_id` when both are supplied.
 */
providerIds?: string[]; systemPromptOverride: string | null; toolAllowlist: string[]; requiredCapabilities?: CapabilityDto[]; temperature: number | null; maxTokens: number | null; 
/**
 * Free-form extras; the `agent_profile_id` key binds a CLI agent
 * profile (SPEC team-shell-m1 D2b).
 */
params: JsonValue }
/**
 * A capability-routing probe: resolves a role for the required capability
 * set (optionally creating + immediately cleaning an ephemeral temp role
 * when `dryRun` is false and only a provider can serve).
 */
export type RouteRequestDto = { requiredCapabilities: CapabilityDto[]; preferRoleId: string | null }
export type RouteResultDto = { role: RoleDto; 
/**
 * True when the router created an ephemeral temp role for the request.
 */
createdTemp: boolean }
/**
 * Routing rules mirrored from `nuomi_core::services::RoutingRules`
 * (persisted in `app_settings`).
 */
export type RoutingRulesDto = { preferLocal?: boolean; capabilityOverrides?: Partial<{ [key in CapabilityDto]: string }> }
export type RunDto = { id: string; taskId: string; sessionId: string; status: string; heartbeatAt: number; kind: string; cancelable: boolean }
export type RunResultDto = { finalText: string; steps: number; truncated: boolean; sessionId: string }
export type ScheduleDto = { id: string; name: string; cronExpr: string; taskTitle: string; taskDescription: string; enabled: boolean; targetKind: string; agent: AgentRefDto | null; teamId: string | null; sessionMode: string; sessionId: string | null; autoDispatch: boolean; lastTriggeredAt: number | null; nextTriggerAt: number | null }
export type ScheduleInput = { name: string; cronExpr: string; targetKind: string; agent: AgentRefInput | null; teamId: string | null; sessionMode: string; sessionId: string | null; autoDispatch: boolean; taskTitle: string; taskDescription: string }
/**
 * Outcome counts of a preset seeding pass.
 */
export type SeedRolesDto = { inserted: number; updated: number; skipped: number }
export type SessionDto = { id: string; title: string; createdAt: number; updatedAt: number }
export type SkillCreationConfigDto = { enabled: boolean; format: SkillFormatDto }
export type SkillFormatDto = "skill_md"
export type TaskDto = { id: string; sessionId: string | null; title: string; description: string; status: string; createdAt: number; updatedAt: number }
export type TeamDto = { id: string; name: string; topology: TeamTopologyDto; memberRoleIds: string[]; config: JsonValue; createdAt: number; updatedAt: number }
export type TeamInput = { name: string; topology: TeamTopologyDto; memberRoleIds: string[]; 
/**
 * Topology-specific config (`max_rounds`, selector settings, ...).
 */
config: JsonValue }
/**
 * Dry-run projection of a validated formation plan: what a commit would
 * build, without touching roles/teams/events (打磨③a).
 */
export type TeamPlanDto = { topology: TeamTopologyDto; members: TeamPlanMemberDto[]; maxRounds: number | null; required: string[]; rationale: string }
export type TeamPlanMemberDto = { kind: string; refId: string; name: string; willCreateRole: boolean }
export type TeamRunResultDto = { finalOutput: string; converged: boolean; rounds: number }
export type TeamTopologyDto = "pipeline" | "router" | "group_chat"
export type TestIntegrationDto = { ok: boolean; error: string | null }
export type TestProviderConnectionDto = { ok: boolean; latencyMs: number | null; error: string | null }
export type TestProviderConnectionInput = { 
/**
 * When set and `api_key` is empty, the stored keyring secret is used.
 */
providerId: string | null; protocol: ProviderProtocolDto; baseUrl: string; apiKey: string | null; 
/**
 * Overrides the stored per-provider proxy when non-empty.
 */
proxy: string | null; 
/**
 * Model for the minimal chat probe; protocol defaults apply when empty.
 */
model: string | null }
export type TodoItemDto = { id: string; description: string; completed: boolean }
export type WhiteBoardNoteDto = { id: string; sessionId: string; authorRoleId: string | null; noteType: string; body: string; refs: JsonValue; seq: number; createdAt: number }
/**
 * A registered workspace entry as seen by the frontend. `directory_present`
 * is a runtime probe (the root dir may have been deleted out-of-band).
 */
export type WorkspaceEntryDto = { id: string; rootPath: string; colorTag: string; createdAt: number; isActive: boolean; directoryPresent: boolean }
/**
 * Workspace contract: the active sandbox root plus whether the workspace has
 * been configured (`app_settings` row exists or `NUOMI_WORKSPACE_ROOT` env
 * was set at boot). `configured=false` gates first-launch setup in the UI.
 */
export type WorkspaceInfo = { root: string; configured: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
