// @ts-nocheck
// GENERATED BY `pnpm contracts:gen` — DO NOT EDIT.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async createSession() : Promise<Result<SessionDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSessions() : Promise<Result<SessionDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeSession(sessionId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEvents(sessionId: string, afterSeq: number) : Promise<Result<EventDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_events", { sessionId, afterSeq }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async submitTask(sessionId: string, input: string) : Promise<Result<RunResultDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_task", { sessionId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTask(title: string, description: string) : Promise<Result<TaskDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_task", { title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTasks(status: string | null) : Promise<Result<TaskDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tasks", { status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTaskStatus(taskId: string, status: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_task_status", { taskId, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRun(runId: string) : Promise<Result<RunDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_run", { runId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRunsByTask(taskId: string) : Promise<Result<RunDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_runs_by_task", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPendingApprovals() : Promise<Result<ApprovalDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_pending_approvals") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveApproval(approvalId: string, approved: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_approval", { approvalId, approved }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDir(path: string) : Promise<Result<FileEntryDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(path: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFile(path: string, content: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStatus() : Promise<Result<GitStatusDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitLog(limit: number) : Promise<Result<GitCommitDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_log", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitStage(paths: string[]) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_stage", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitCommit(message: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_commit", { message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPush(remote: string, branch: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_push", { remote, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitWorktrees() : Promise<Result<GitWorktreeDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_worktrees") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSchedule(name: string, cronExpr: string, taskTitle: string, taskDescription: string) : Promise<Result<ScheduleDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_schedule", { name, cronExpr, taskTitle, taskDescription }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSchedules() : Promise<Result<ScheduleDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_schedules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleSchedule(scheduleId: string, enabled: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_schedule", { scheduleId, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSchedule(scheduleId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_schedule", { scheduleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertProvider(provider: ProviderInput) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviders() : Promise<Result<ProviderDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_providers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSensitiveTools(patterns: string[]) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sensitive_tools", { patterns }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSensitiveTools() : Promise<Result<string[] | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sensitive_tools") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOnlineAuthorized(authorized: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_online_authorized", { authorized }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOnlineAuthorized() : Promise<Result<boolean, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_online_authorized") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWorkspace() : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWorkspace(path: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_workspace", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgentProfiles() : Promise<Result<AgentProfileDto[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agent_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertAgentProfile(profile: AgentProfileInput) : Promise<Result<AgentProfileDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_agent_profile", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAgentProfile(profileId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_agent_profile", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkCliAgent(profileId: string) : Promise<Result<CliAgentCheckDto, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_cli_agent", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentProfileDto = { id: string; name: string; adapter: string; flavor: CliFlavorDto; command: string; args: string[]; env: Partial<{ [key in string]: string }>; workingDir: string | null; enabled: boolean; createdAt: number; updatedAt: number }
export type AgentProfileInput = { name: string; flavor: CliFlavorDto; command: string; args: string[]; env: Partial<{ [key in string]: string }>; workingDir: string | null; enabled: boolean }
export type ApprovalDto = { id: string; runId: string; toolName: string; argumentsJson: string }
export type CliAgentCheckDto = { ok: boolean; versionLine: string | null; error: string | null }
export type CliFlavorDto = "claude_code" | "codex" | "plain"
export type EventDto = { seq: number; kind: string; payload: JsonValue; createdAt: number }
export type FileEntryDto = { name: string; isDir: boolean; size: number }
export type GitCommitDto = { hash: string; subject: string; author: string }
export type GitStatusDto = { indexStatus: string; worktreeStatus: string; path: string }
export type GitWorktreeDto = { path: string; head: string | null; branch: string | null; isCurrent: boolean }
/**
 * Outward-facing error for every command.
 */
export type IpcError = { generic: { code: string; message: string; details?: JsonValue | null } }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type ProviderDto = { id: string; name: string; protocol: ProviderProtocolDto; baseUrl: string; hasKey: boolean; capabilities: string[]; isMaster: boolean }
export type ProviderInput = { name: string; protocol: ProviderProtocolDto; baseUrl: string; capabilities: string[]; isMaster: boolean; 
/**
 * Plaintext only in transit — stored straight into the OS keyring,
 * never persisted to SQLite or logs.
 */
apiKey: string | null }
export type ProviderProtocolDto = "open_ai_compatible" | "anthropic_compatible"
export type RunDto = { id: string; taskId: string; sessionId: string; status: string; heartbeatAt: number }
export type RunResultDto = { finalText: string; steps: number; truncated: boolean; sessionId: string }
export type ScheduleDto = { id: string; name: string; cronExpr: string; taskTitle: string; enabled: boolean; nextTriggerAt: number | null }
export type SessionDto = { id: string; title: string; createdAt: number; updatedAt: number }
export type TaskDto = { id: string; sessionId: string | null; title: string; description: string; status: string; createdAt: number; updatedAt: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
