//! Nuomi desktop shell: thin Tauri layer over nuomi-core.
//!
//! - Commands: `#[tauri::command]` wrappers that delegate to `commands::*`
//!   free functions (testable without a Tauri runtime).
//! - Contracts: single tauri-specta builder; TS bindings exported to
//!   `../src/lib/ipc/bindings.gen.ts`.
//! - Events: kernel bus → ADR-0002 multi-channel emit (see `events.rs`).

pub mod commands;
mod events;
mod ipc_error;
pub mod state;
mod tauri_cmds;

pub use ipc_error::{codes, IpcError};

use tauri::{Emitter, Manager};
use tauri_specta::{collect_commands, Builder};

use state::AppState;

// ---------- contracts ----------

// The single specta collection point (ipc-contract rule).
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        tauri_cmds::create_session,
        tauri_cmds::list_sessions,
        tauri_cmds::resume_session,
        tauri_cmds::list_events,
        tauri_cmds::submit_task,
        tauri_cmds::create_task,
        tauri_cmds::list_tasks,
        tauri_cmds::update_task_status,
        tauri_cmds::get_run,
        tauri_cmds::list_runs_by_task,
        tauri_cmds::list_pending_approvals,
        tauri_cmds::resolve_approval,
        tauri_cmds::list_dir,
        tauri_cmds::read_file,
        tauri_cmds::write_file,
        tauri_cmds::git_status,
        tauri_cmds::git_log,
        tauri_cmds::git_stage,
        tauri_cmds::git_commit,
        tauri_cmds::git_push,
        tauri_cmds::git_worktrees,
        tauri_cmds::create_schedule,
        tauri_cmds::list_schedules,
        tauri_cmds::toggle_schedule,
        tauri_cmds::delete_schedule,
        tauri_cmds::upsert_provider,
        tauri_cmds::list_providers,
        tauri_cmds::set_sensitive_tools,
        tauri_cmds::get_sensitive_tools,
        tauri_cmds::set_online_authorized,
        tauri_cmds::get_online_authorized,
        tauri_cmds::get_workspace,
        tauri_cmds::set_workspace,
        tauri_cmds::list_agent_profiles,
        tauri_cmds::upsert_agent_profile,
        tauri_cmds::delete_agent_profile,
        tauri_cmds::check_cli_agent,
        tauri_cmds::list_roles,
        tauri_cmds::upsert_role,
        tauri_cmds::delete_role,
        tauri_cmds::list_teams,
        tauri_cmds::upsert_team,
        tauri_cmds::delete_team,
        tauri_cmds::list_whiteboard_notes,
        tauri_cmds::form_team,
        tauri_cmds::run_team_on_task,
        tauri_cmds::run_team_session,
    ])
}

/// Standalone bindings export (`pnpm contracts:gen`).
pub fn export_bindings() -> Result<(), Box<dyn std::error::Error>> {
    specta_builder().export(
        specta_typescript::Typescript::default()
            .bigint(specta_typescript::BigIntExportBehavior::Number)
            .header("// @ts-nocheck\n// GENERATED BY `pnpm contracts:gen` — DO NOT EDIT."),
        "src/lib/ipc/bindings.gen.ts",
    )?;
    Ok(())
}

/// Forwards one kernel event onto the right Tauri channel(s).
async fn forward_event(
    app: tauri::AppHandle,
    mut rx: tokio::sync::broadcast::Receiver<nuomi_core::harness::Event>,
) {
    loop {
        match rx.recv().await {
            Ok(ev) => {
                for (channel, wire) in events::partition_event(&ev) {
                    if let Err(e) = app.emit(&channel, wire) {
                        tracing::warn!(error = %e, channel = %channel, "emit failed");
                    }
                }
            }
            Err(tokio::sync::broadcast::error::RecvError::Lagged(n)) => {
                tracing::warn!(skipped = n, "event bridge lagged");
            }
            Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
        }
    }
}

pub fn run() {
    let builder = specta_builder();
    #[cfg(debug_assertions)]
    if let Err(e) = export_bindings() {
        eprintln!("bindings export failed: {e}");
    }

    tauri::Builder::default()
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let db_path = std::env::var_os("NUOMI_DB_PATH")
                .map(std::path::PathBuf::from)
                .unwrap_or_else(|| {
                    app.path()
                        .app_data_dir()
                        .unwrap_or_else(|_| std::path::PathBuf::from("."))
                        .join("nuomi.db")
                });
            let api_key = std::env::var("NUOMI_API_KEY").unwrap_or_default();
            let base_url = std::env::var("NUOMI_BASE_URL")
                .unwrap_or_else(|_| "https://api.openai.com/v1".to_string());
            let model = std::env::var("NUOMI_MODEL").unwrap_or_else(|_| "gpt-4o-mini".to_string());
            let provider = nuomi_core::facade::ProviderSource::Endpoint(
                nuomi_core::facade::ProviderEndpoint {
                    protocol: nuomi_core::domain::ProviderProtocol::OpenAiCompatible,
                    base_url,
                    api_key,
                    model,
                },
            );
            let state = tauri::async_runtime::block_on(AppState::boot(db_path, provider))
                .map_err(|e| format!("kernel boot failed: {e}"))?;

            // Event bridge: kernel bus → ADR-0002 channels.
            let rx = state.kernel.context().subscribe();
            let handle = app.handle().clone();
            tauri::async_runtime::spawn(forward_event(handle, rx));

            // Scheduler background runner.
            let runner = nuomi_core::services::SchedulerRunner::new(
                state.db_path.clone(),
                std::time::Duration::from_secs(5),
            )
            .spawn();
            app.manage(runner);

            app.manage(state);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running nuomi shell");
}
